Docs/fixes based on feedback
Soyio-id/soyio-docs pull request #28
Opened 2024-11-14 16:02 UTC by jmaldonadof

- Incorpora los cambios sugeridos por Edison
- Corrige el ejemplo de los matchers
- Agrega una tabla con los campos por los que se puede hacer match y el formato que acepta.

2024-11-14 16:31 UTC, MatiMenich requested changes
Buenas, te dejé un par de comentarios.

2024-11-14 16:31 UTC, MatiMenich commented on docs/integration-guide/concepts/consent.md
> +La primera etapa implica solicitar el consentimiento del usuario. Este proceso debe cumplir con los principios LEII. El usuario recibe toda la información necesaria sobre el propósito y uso de sus da
Acá quizá sería bueno poner un link a los principios LEII

2024-11-14 16:31 UTC, MatiMenich commented on docs/integration-guide/concepts/glossary.md
> +#### Derechos que se incluirán con la futura Ley de Protección de Datos en Chile
Creo que esto podría ser un admonition con la banderita de Chile. Me gustaría mantener la docu mas neutra en base al país

2024-11-14 16:31 UTC, MatiMenich commented on docs/integration-guide/modules/disclosure.mdx
> +| --- | --- |
Creo que esto debiera estar especificado en el spec del API tmb.

2024-11-14 16:31 UTC, MatiMenich commented on docs/user-guide/faq.md
> +Sí, los documentos firmados a través de Soyio cumplen con los requisitos de firma electrónica simple (FES).
Esto en el caso de Chile.

2024-11-14 17:44 UTC, jmaldonadof commented on docs/user-guide/faq.md
> +Sí, los documentos firmados a través de Soyio cumplen con los requisitos de firma electrónica simple (FES).
Yo creo que también cumple con la firma electronica simple y quizás avanzada de otros países. https://www.entrust.com/es/resources/learn/eidas
Pero lo que viene después de esta línea (las excepciones) si está sacado de la reglamentación chilena.

2024-11-14 22:19 UTC, MatiMenich commented on docs/user-guide/faq.md
> +Sí, los documentos firmados a través de Soyio cumplen con los requisitos de firma electrónica simple (FES).
Dale, entonces creo que podríamos ser más generales nomás

2024-11-15 22:16 UTC, jmaldonadof commented on docs/user-guide/faq.md
> +Sí, los documentos firmados a través de Soyio cumplen con los requisitos de firma electrónica simple (FES).
Al final igual modifiqué esto para que no fuera tan especifico para Chile y la definición de FES más arriba en este mismo archivo.

2024-11-16 01:56 UTC, MatiMenich commented on docs/api/resources/create-disclosure-request.api.mdx
Como no fue mediante generación, el ejemplo quedó igual. Habría que modificar la línea 57 con lo mismo que se puso en los parámetros

2024-11-16 01:56 UTC, MatiMenich commented on src/theme/Admonition/Types.js
Ojo que no es necesario extender los admonitions si es sólo el ícono (no vi otra cosa pero puedo estar equivocado), ya que según tengo entendido, se puede definir el ícono a nivel de declaración, pero como componente (es necesario mdx si). Así:
```jsx
<Admonition type="note" icon="🇨🇱" title="En Chile">
  Contenido de Chile acá...
</Admonition>
```

 Acá la referencia: https://docusaurus.io/docs/markdown-features/admonitions#usage-in-jsx

2024-11-18 21:43 UTC, MatiMenich reviewed
Lo veo todo ok. Solo veo ese typo que te comenté, pero cambinado eso estamos (y preocuparse de actualziar el spec en el monolito)

2024-11-18 21:43 UTC, MatiMenich commented on docs/api/resources/index-signed-documents.api.mdx
> +description: "Retorna una lista de documentos firmados. Los documentod se encuentran ordenadas por defecto por la fecha de creación, donde las mas recientes aparecerán primero."
creo que el spec está malo y lo habíamos arreglado manualmente 😓

2024-11-18 21:48 UTC, jmaldonadof commented on docs/api/resources/index-signed-documents.api.mdx
> +description: "Retorna una lista de documentos firmados. Los documentod se encuentran ordenadas por defecto por la fecha de creación, donde las mas recientes aparecerán primero."
Listo 👍🏼

2024-11-19 01:13 UTC, MatiMenich approved these changes

2024-11-19 01:13 UTC, merged